version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG

  file:
    class: logging.FileHandler
    filename: logs/app.log
    formatter: standard
    level: INFO

loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [console, file]
    level: INFO
    propagate: False

  django:
    handlers: [console, file]
    level: DEBUG
    propagate: False

  django.request:
    handlers: [console, file]
    level: DEBUG
    propagate: False

root:
  handlers: [console, file]
  level: DEBUG

