# # """
# # Django settings for HomieGramBackEnd project.

# # Generated by 'django-admin startproject' using Django 5.0.2.

# # For more information on this file, see
# # https://docs.djangoproject.com/en/5.0/topics/settings/

# # For the full list of settings and their values, see
# # https://docs.djangoproject.com/en/5.0/ref/settings/
# # """

# # from pathlib import Path

# # # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # BASE_DIR = Path(__file__).resolve().parent.parent


# # # Quick-start development settings - unsuitable for production
# # # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# # # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = 'django-insecure-wz1s%bi$+y*#n4@42c+s3oq@f!jid@nnu&2n0k5a8q*)ncp5ck'

# # # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True

# # ALLOWED_HOSTS = ['192.168.0.107', '127.0.0.1', 'localhost', '192.168.8.18', '172.20.10.2', '192.168.2.127', "http://hommiegram.azurewebsites.net/", '192.168.21.219', '192.168.100.7', '192.168.100.18', '192.168.0.107', '192.168.100.18', '192.168.100.11']
# # # CSRF_TRUSTED_ORIGINS = [
# # #     "https://hommiegram.azurewebsites.net",
# # #     "http://localhost:8000",
# # #     "http://127.0.0.1:8000",
# # # ]


# # # Application definition

# # INSTALLED_APPS = [
# #      'daphne',
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',
# #     # Installed Apps
# #     'rest_framework',
# #     'knox',
# #     # Custom apps
# #     'accounts.apps.AccountsConfig',
# #     'houses.apps.HousesConfig',
# #     'comments.apps.CommentsConfig',
# #     'business.apps.BusinessConfig',
  
# #     'chat.apps.ChatConfig'
   

   
# # ]


# # ROOT_URLCONF = 'HomieGramBackEnd.urls'

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.debug',
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #             ],
# #         },
# #     },
# # ]

# # WSGI_APPLICATION = 'HomieGramBackEnd.wsgi.application'


# # # Database
# # # https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# # # CUSTOM USER
# # AUTH_USER_MODEL = "accounts.CustomUser"

# # # Password validation
# # # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# # AUTH_PASSWORD_VALIDATORS = [
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
# #     },
# # ]


# # # Internationalization
# # # https://docs.djangoproject.com/en/5.0/topics/i18n/

# # LANGUAGE_CODE = 'en-us'

# # TIME_ZONE = 'UTC'

# # USE_I18N = True

# # USE_TZ = True


# # # Static files (CSS, JavaScript, Images)
# # # https://docs.djangoproject.com/en/5.0/howto/static-files/


# # # percistent directiry.
# # STATIC_URL = 'static/'
# # STATIC_ROOT = BASE_DIR / 'static'

# # MEDIA_URL = '/media/'
# # MEDIA_ROOT = BASE_DIR / "house_images"

# # # Default primary key field type
# # # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# # DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # REST_FRAMEWORK = {
# #     'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',)
# #     ,
# # 'DEFAULT_PERMISSION_CLASSES': [
# #     'rest_framework.permissions.IsAuthenticated',
# # ]
# # }

# # CHANNEL_LAYERS = {
# #     'default': {
# #         'BACKEND': 'channels_redis.core.RedisChannelLayer',
# #         'CONFIG': {
# #             'hosts': [('127.0.0.1', 6379)],  # Ensure Redis is running
# #         },
# #     },
# # }

# # # # For now use in-memory layer (can use Redis in production)
# # # CHANNEL_LAYERS = {
# # #     "default": {
# # #         "BACKEND": "channels.layers.InMemoryChannelLayer"
# # #     }
# # # }

# # REST_KNOX = {
# #     'TOKEN_TTL': None,  # Token does not expire
# # }

# # ASGI_APPLICATION = "HomieGramBackEnd.asgi.application"

# from pathlib import Path
# import os
# import environ

# BASE_DIR = Path(__file__).resolve().parent.parent

# # Initialise environment variables
# env = environ.Env(
#     DEBUG=(bool, False)  # default DEBUG = False
# )

# # Read the .env file if it exists
# environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env("SECRET_KEY")

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = env("DEBUG")

# ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

# # Application definition
# INSTALLED_APPS = [
#     "daphne",
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     # Installed Apps
#     "rest_framework",
#     "knox",
#     # Custom apps
#     "accounts.apps.AccountsConfig",
#     "houses.apps.HousesConfig",
#     "comments.apps.CommentsConfig",
#     "business.apps.BusinessConfig",
#     "chat.apps.ChatConfig",
# ]

# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = "HomieGramBackEnd.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "HomieGramBackEnd.wsgi.application"

# # Database (now loaded from DATABASE_URL)
# DATABASES = {
#     "default": env.db("DATABASE_URL")
# }

# # CUSTOM USER
# AUTH_USER_MODEL = "accounts.CustomUser"

# # Password validation
# AUTH_PASSWORD_VALIDATORS = [
#     {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
#     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
#     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
#     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
# ]

# # Internationalization
# LANGUAGE_CODE = "en-us"
# TIME_ZONE = "UTC"
# USE_I18N = True
# USE_TZ = True

# # Static & media
# STATIC_URL = "static/"
# STATIC_ROOT = BASE_DIR / "static"

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "house_images"

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# # DRF + Knox
# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": ("knox.auth.TokenAuthentication",),
#     "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
# }

# # Channels / Redis
# REDIS_URL = env("REDIS_URL", default="redis://127.0.0.1:6379/0")
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {"hosts": [REDIS_URL]},
#     }
# }

# REST_KNOX = {"TOKEN_TTL": None}  
# ASGI_APPLICATION = "HomieGramBackEnd.asgi.application"
